sudo: false
language: php

php:
  - 7.3

deploy:
  - provider: script
    skip_cleanup: true
    script: chmod +x $TRAVIS_BUILD_DIR/scripts/deploy.sh && $TRAVIS_BUILD_DIR/scripts/deploy.sh
    on:
      branch: master
      php: 7.3
